#!/bin/bash

IPADDR=`wget -q -O - checkip.dyndns.com | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
if [ $? -ne 0 ]; then echo "DNS WARNING: cannot detect ip address!"; exit 1; fi

MSG=`/usr/lib/nagios/plugins/check_dns -H futurama.mine.nu -s 8.8.8.8 -a $IPADDR`
RES=$?

OUT=`echo "$MSG" | egrep '^DNS CRITICAL.*'`
if [ $? -ne 0 ]; then
	echo "$MSG"
	exit $RES
else
	sudo /usr/sbin/ddclient -syslog -ip $IPADDR &> /dev/null
	echo "DYNDNS CRITICAL futurama.mine.nu does not resolve to $IPADDR, trying to update dyndns now"
	exit 2
fi

