#!/bin/bash

interface="$1"
fix='false'

# ignore verbose options
while getopts ":vfh" opt; do
	if [ "$opt" = "f" ]; then
		fix='true'
	elif [ "$opt" = "h" ]; then
		echo "Usage: $0 [-hf]"
		echo ""
		echo "-f use experimental ways to fix errors"
		echo "-h display this help text"
		echo ""
		exit 3
	fi
	shift $((OPTIND-1))
done

if [ "$fix" = "true" ]; then
	echo "-f supplied, trying to fix any errors"
fi

if [ "${interface}" == "" ]; then
	echo "ERROR - Please supply an interface"
	exit 3
fi

if [ "$2" != "" ]; then
	echo "Too many arguments!"
	exit 3
fi

# get kernel id
real_id=$(ip addr | grep -o "[0-9]*: ${interface}" | grep -o '^[0-9]*')

if [ "$real_id" == "" ]; then
	echo "Interface does not exist!"
	exit 3
fi

# get snmp id
snmp_id=$(snmpwalk -On -c public -v 2c localhost .1.3.6.1.2.1.2.2.1.2 | \
	grep internet | \
	sed 's/^\.1.3.6.1.2.1.2.2.1.2.\([0-9]\{1,3\}\) = STRING: '${interface}'/\1/g')

if [ "$real_id" != "$snmp_id" ]; then
	echo "CRITICAL - kernel and SNMP interface IDs for \"${interface}\" do not match. Restarting snmpd..."
	sudo /usr/sbin/service snmpd restart &> /dev/null
	exit 2
fi

# get cacti id
cacti_ids=$(mysql -u root cacti -e "select arg1 from poller_item where rrd_path = '/var/lib/cacti/rra/localhost_traffic_in_45.rrd'" | \
	egrep '.1.3.6.1.2.1.2.2.1.(10|16).[0-9]+' | \
	egrep -o '[0-9]*$')

# check the ids match
res=0
for cacti_id in $cacti_ids; do
	if [ "$snmp_id" != "$cacti_id" ]; then
		res=2
	fi
done

# report the result
if [ $res -eq 0 ]; then
	echo "OK - Interface IDs for \"$interface\" match"
	exit 0
else
	if [ "$fix" = "true" ]; then
		echo "CRITICAL - Cacti and SNMP interface IDs for \"$interface\" don't match. Updating cacti database entries."
		cacti_ids=$(mysql -u root cacti -e "SELECT arg1 FROM poller_item WHERE rrd_path = '/var/lib/cacti/rra/localhost_traffic_in_45.rrd'" | \
			egrep '.1.3.6.1.2.1.2.2.1.(10|16).[0-9]+')
		for cacti_id in $cacti_ids; do
			new_id=$(echo "$cacti_id" | sed "s/[0-9]*$/$real_id/")
			echo $(mysql -u root cacti -e "UPDATE poller_item SET arg1='$new_id' WHERE arg1='$cacti_id'")
		done
	else
		echo "CRITICAL - Cacti and SNMP interface IDs for \"$interface\" no longer match! Graphs will not be generated!"
	fi
	exit 2
fi
